### ISSUE TITLE
app crash on startup,android permissions issue

### ISSUE THREAD

**Issue by QGB** [lincoln1clarke/KivyJniusBluetoothApp#1]
@lincoln1clarke 
logcat shows
```

[HWC] (0) displayGetActiveConfig config:0
[HWCDisplay] [Display_0 (type:1)] fps:2.272003,dur:1320.42,max:880.77,min:16.24
[WARNING] [Base ] Unknown <android> provider
[INFO ] [Base ] Start application main loop
[INFO ] [Base ] Leaving application in progress...
Traceback (most recent call last):
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/app/main.py", line 370, in <module>
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/app.py", line 955, in run
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/base.py", line 574, in runTouchApp
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/base.py", line 339, in mainloop
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/base.py", line 379, in idle
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/clock.py", line 733, in tick
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/kivy/clock.py", line 776, in post_idle
File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
File "/home/user/KivyJniusBluetoothApp/.buildozer/android/app/main.py", line 356, in start
File "jnius/jnius_export_class.pxi", line 885, in jnius.jnius.JavaMethod.__call__
File "jnius/jnius_export_class.pxi", line 982, in jnius.jnius.JavaMethod.call_method
File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
jnius.jnius.JavaException: JVM exception occurred: Need BLUETOOTH permission: Neither user 10183 nor current process has android.permission.BLUETOOTH. java.lang.SecurityException
Python for android ended.
04-27 04:54:46.721 BL= 139,ESS= 256, 04-27 04:54:46.819 BL= 138,ESS= 256, 04-27 04:54:46.902 BL= 137,ESS= 256, 04-27 04:54:47.004 BL= 136,ESS= 256, 04-27 04:54:47.088 BL= 135,ESS= 256,
RefBase: Explicit destruction, weak count = 0 (in 0xee0e60d8)
CallStack::getCurrentInternal not linked, returning null
CallStack::logStackInternal not linked
channel 'd4d5045 org.test.myapp/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred. events=0x9
channel 'd4d5045 org.test.myapp/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
for fd 16, revents = 2011
[org.test.myapp/org.kivy.android.PythonActivity#0](this:0xe619d000,id:2774,api:1,p:13868,c:567) disconnect(P): api 1
[SurfaceView - org.test.myapp/org.kivy.android.PythonActivity#0](this:0xe62aa000,id:2776,api:1,p:13868,c:567) disconnect(P): api 1
enable: handle:0, en:0
Destroy ARC handle: 0xc3196970
Process 13868 exited cleanly (255)
WIN DEATH: Window{d4d5045 u0 org.test.myapp/org.kivy.android.PythonActivity}
Attempted to unregister already unregistered input channel 'd4d5045 org.test.myapp/org.kivy.android.PythonActivity (server)'
Process org.test.myapp (pid 13868) has died: fore TOP
Successfully killed process cgroup uid 10183 pid 13868 in 0ms
Background young concurrent copying GC freed 74697(3367KB) AllocSpace objects, 9(436KB) LOS objects, 5% free, 47MB/50MB, paused 487us total 131.103ms
[org.test.myapp/org.kivy.android.PythonActivity#0](this:0xe619d000,id:2774,api:1,p:-1,c:-1) ~BufferQueueCore
[Bounds for - org.test.myapp/org.kivy.android.PythonActivity#0](this:0xe61a4000,id:2775,api:0,p:-1,c:-1) ~BufferQueueCore
[SurfaceView - org.test.myapp/org.kivy.android.PythonActivity#0](this:0xe62aa000,id:2776,api:1,p:-1,c:-1) ~BufferQueueCore
Force removing ActivityRecord{7883b56 u0 org.test.myapp/org.kivy.android.PythonActivity t6700}: app died, no saved state
[perfNotifyAppState] pack:org.test.myapp, pid:13868, STATE_DEAD
notify_rild_crash_pid_set certPid:-1, crash:13868, scn:0x0
phwperfLockAcq
```

**Comment by lincoln1clarke** [comment]
When you compile it for android with Buildozer, you need to add Bluetooth permissions.  If you have modified this app or integrated part of it into your code, then you will need to compile it yourself.  Otherwise, here is the compiled version of this one (APK): [https://drive.google.com/file/d/1hkj8SJV0N-LGHeP1JYtRS4f6Z0nU_KFd/view?usp=sharing](url)

If you are compiling it yourself, you need permissions BLUETOOTH and BLUETOOTH_ADMIN.

Here is a copy of the spec file I used, but read through it and change what you need because there will be some things like file paths that are different.
[Spec file for Bluetooth Kivy RC control.txt](https://github.com/lincoln1clarke/KivyJniusBluetoothApp/files/11343061/Spec.file.for.Bluetooth.Kivy.RC.control.txt)

Hopefully this helps!
